# Generated by Django 5.1.15 on 2026-05-27 20:07

import apps.domains.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('tld', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('vaulted', 'Vaulted'), ('sharding', 'Sharding in Progress'), ('active', 'Active Campaign'), ('completed', 'Funding Completed'), ('withdrawn', 'Withdrawn')], db_index=True, default='pending', max_length=20)),
                ('verification_nonce', models.CharField(default=apps.domains.models._new_verification_nonce, editable=False, help_text='Founder must publish this value in a TXT record on _yurika-verify.<fqdn>.', max_length=32)),
                ('ownership_proof_url', models.URLField(blank=True)),
                ('registrar', models.CharField(blank=True, max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('vault_contract_address', models.CharField(blank=True, max_length=42)),
                ('shard_contract_address', models.CharField(blank=True, max_length=42)),
                ('chain_id', models.IntegerField(default=8453)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='domains', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'domains',
                'ordering': ['-created_at'],
            },
        ),
    ]
