# Generated by Django 5.1.15 on 2026-05-27 21:15

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domains', '0002_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShardCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('thesis', models.TextField()),
                ('total_shards', models.BigIntegerField()),
                ('shards_available', models.BigIntegerField()),
                ('price_per_shard_usd', models.DecimalField(decimal_places=6, max_digits=18)),
                ('funding_target_usd', models.DecimalField(decimal_places=2, max_digits=18)),
                ('funding_raised_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('governance_enabled', models.BooleanField(default=True)),
                ('quorum_percentage', models.IntegerField(default=51)),
                ('forge_stage', models.CharField(blank=True, max_length=100)),
                ('domain', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='campaign', to='domains.domain')),
            ],
            options={
                'db_table': 'shard_campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShardHolding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shards_held', models.BigIntegerField()),
                ('purchase_price_usd', models.DecimalField(decimal_places=6, max_digits=18)),
                ('tx_hash', models.CharField(blank=True, max_length=66)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holdings', to='marketplace.shardcampaign')),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shard_holdings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shard_holdings',
                'ordering': ['-created_at'],
                'unique_together': {('campaign', 'holder')},
            },
        ),
    ]
